services:
 -docker 
 
 before install:
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t udagram-reverseproxy ./udagram-reverseproxy

# Tagging
- docker tag udagram-api-feed ryangambinga/udagram-api-feed:v1
- docker tag udagram-api-user ryangambinga/udagram-api-user:v1
- docker tag udagram-frontend ryangambinga/udagram-frontend:v1
- docker tag udagram-reverseproxy ryangambinga/udagram-reverseproxy:v1

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push ryangambinga/udagram-api-feed:v1
- docker push ryangambinga/udagram-api-user:v1
- docker push ryangambinga/udagram-frontend:v1
- docker push ryangambinga/udagram-api-reverseproxy:v1