#  secret
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret # Name of the secret
  namespace: default # Namespace of the secret
data:
  aws_access_key_id: QVNJQVU3TlJOVzVVWVNBU0FaVVY=
  aws_secret_access_key: T2c3dUdSSWE4UUs3SDA0ZmF1M3BCZlA2bEQ4QzVZeUpXcXcwK3V5Sw== # AWS secret access key (base64 encoded)
type: Opaque